14:29:14 > Referencia a objeto no establecida como instancia de un objeto.
14:30:12 > Referencia a objeto no establecida como instancia de un objeto.
14:31:09 > Referencia a objeto no establecida como instancia de un objeto.
14:32:32 > Referencia a objeto no establecida como instancia de un objeto.
14:32:34 > Se produjo una excepción en el destino de la invocación.
14:33:23 > Referencia a objeto no establecida como instancia de un objeto.
14:34:28 > Referencia a objeto no establecida como instancia de un objeto.
14:34:38 > Se produjo una excepción en el destino de la invocación.
14:35:10 > Referencia a objeto no establecida como instancia de un objeto.
14:35:50 > Referencia a objeto no establecida como instancia de un objeto.
14:37:34 > Referencia a objeto no establecida como instancia de un objeto.
14:37:57 > Referencia a objeto no establecida como instancia de un objeto.
14:37:59 > Se produjo una excepción en el destino de la invocación.
14:38:21 > Se produjo una excepción en el destino de la invocación.
14:38:23 > Se produjo una excepción en el destino de la invocación.
14:38:51 > Se produjo una excepción en el destino de la invocación.
14:46:18 > Referencia a objeto no establecida como instancia de un objeto.
14:46:20 > Se produjo una excepción en el destino de la invocación.
14:47:55 > Referencia a objeto no establecida como instancia de un objeto.
14:50:14 > Referencia a objeto no establecida como instancia de un objeto.
14:51:10 > Referencia a objeto no establecida como instancia de un objeto.
14:51:56 > Referencia a objeto no establecida como instancia de un objeto.
14:53:28 > Se produjo una excepción en el destino de la invocación.
14:54:40 > Referencia a objeto no establecida como instancia de un objeto.
14:54:43 > Se produjo una excepción en el destino de la invocación.
14:57:09 > Referencia a objeto no establecida como instancia de un objeto.
14:57:14 > Se produjo una excepción en el destino de la invocación.
14:58:17 > Referencia a objeto no establecida como instancia de un objeto.
14:59:48 > Se produjo una excepción en el destino de la invocación.
15:00:35 > Se produjo una excepción en el destino de la invocación.
15:01:46 > Se produjo una excepción en el destino de la invocación.
15:03:10 > Se produjo una excepción en el destino de la invocación.
15:13:38 > Se produjo una excepción en el destino de la invocación.
15:44:13 > La columna 'PUSERCUID' no pertenece a la tabla Table.
15:47:00 > La columna 'PUSERCUID' no pertenece a la tabla Table.
16:50:10 > No se puede reconocer la cadena como valor DateTime válido.
16:50:13 > No se puede reconocer la cadena como valor DateTime válido.
16:50:58 > No se puede reconocer la cadena como valor DateTime válido.
16:51:01 > No se puede reconocer la cadena como valor DateTime válido.
16:51:29 > No se puede reconocer la cadena como valor DateTime válido.
16:52:20 > No se puede reconocer la cadena como valor DateTime válido.
